### PR TITLE
fix pom.xml

### LINKED ISSUE #2: [ERROR] Failed to execute goal on project wechaty-examples
I got this error message when I running `make install`:

> [ERROR] Failed to execute goal on project wechaty-examples: Could not resolve dependencies for project io.github.wechaty:wechaty-examples:jar:1.0.0-SNAPSOHOT: Failure to find io.wechaty:wechaty:jar:1.0.0-SNAPSOHOT in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Full log messages:

```sh
$ make install
mvn clean install -f examples/pom.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< io.github.wechaty:wechaty-examples >-----------------
[INFO] Building wechaty-examples 1.0.0-SNAPSOHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.wechaty:wechaty:jar:1.0.0-SNAPSOHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.192 s
[INFO] Finished at: 2020-05-21T11:10:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wechaty-examples: Could not resolve dependencies for project io.github.wechaty:wechaty-examples:jar:1.0.0-SNAPSOHOT: Failure to find io.wechaty:wechaty:jar:1.0.0-SNAPSOHOT in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

### PR DESCRIPTION
**Pull request by diaozxin007**
Fixes #2

### CODE REVIEW

File: examples/ding-dong-bot.java [hunk 1]
```diff
@@ -1,4 +0,0 @@
-/**
```
Comment (huan) [inline examples/ding-dong-bot.java:1]: May we keep this file so that a new developer can be easy to find out the main entrance of our Java example, especially a developer who is not very familiar with the Java directory structure?

File: examples/ding-dong-bot.kt [hunk 2]
```diff
@@ -1,4 +0,0 @@
-/**
```
Comment (huan) [inline examples/ding-dong-bot.kt:1]: May we keep this file so that a new developer can be easy to find out the main entrance of our Kotlin example, especially a developer who is not very familiar with the Kotlin directory structure?

**Comment by diaozxin007** [comment]
I think every java developer can understand 'package of java'.And any ide of java can show it well.

**Comment by diaozxin007** [comment]
I think every java developer can understand 'package of java'.And any IDE of java can show it well.

**Comment by diaozxin007** [comment]
eg. https://github.com/vert-x3/vertx-examples

**Comment by huan** [comment]
@diaozxin007 I understand that every java developer will very familiar with this directory layout structure.

My suggestion is from a non-java developers' view. A place holder file with the same name across all the wechaty getting started repositories would be easy to found, and it will act as a clue for newbies of java. For me, it will save a little time when I'm surfing across different projects.

I'm ok with deleting those two files, and my options are just FYI.

Thank you very much for cleaning the java getting started repo, and I'm looking forward to using it to start my first Java/Kotlin bot, cheers!

**Comment by diaozxin007** [comment]
ok，U are right，I will add those file with next pr.

**Comment by huan** [comment]
Let's try our first Java DingDongBot! :tada:
